---
base_url: "https://mysite.com"
static_dir: "static"
per_page: 50

# Each entry can have multiple collection of tags (list of strings) in addition to the
# categories. For instance, a directory of fonts could have multiple meaningful
# tag collections per entry such as:
# types = [serif, sans-serif, display, script]
# mood = [retro, distressed, cool]
# tag = [yep, nope, etc]
taxonomies: ["style", "mood"]

site_name: "My directory site"
site_description: "GuideStar India is India’s largest and most reliable NGO information repository. Our portal www.GuidestarIndia.org is India's most exhaustive, fully searchable database of reliable and comparable information on over 10,000 NGOs. More than 1,400 of these organisations have undergone varying levels of due diligence forming India's largest pool of certified NGOs. With another 60,000+ NGOs on our offline database and NGO due diligence solutions, we have brought down the cost and time of connecting with NGOs. GuideStar India is transforming how Indian NGOs report and share information, and, is changing the way the people perceive, interact and engage with NGOs. "
page_title: "{category} - Directory of cool things."
meta_description: "Directory of {category} in cool things. "
